# config/packages/security.yaml
security:
    # Configure password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # Providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            jwt: ~
            # Optional: if using JWT token storage
            # context: api
            
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      

    # Access control
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
